### ISSUE TITLE
Duplicate Fire Extinguisher

### ISSUE THREAD

**Issue by SirenFreak** [TheRealMcrafter/SirenMod#2]
There is a Duplicate Fire Extinguisher Item in the Creative Inventory. I Operable, 1 not.
![duplicate bug](https://cloud.githubusercontent.com/assets/12742352/7977658/028c0022-0a4a-11e5-82d0-d7423e5ccdab.png)

**Comment by TheRealMcrafter** [comment]
Known, it is for my debugging purposes. Will be removed when I release the final version. Thanks for letting me know though.
