### ISSUE TITLE
Rotating Nuclear Siren

### ISSUE THREAD

**Issue by SirenFreak** [TheRealMcrafter/SirenMod#5]
Version 4.0.1: The Nuclear Siren countinues to rotate after I set it off.

http://www.mediafire.com/watch/6yg65bq821227nb/Rotation_Bug.mp4

**Comment by TheRealMcrafter** [comment]
I cannot seem to duplicate this bug. Can you still do it? Can you explain how to do it?

**Comment by SirenFreak** [comment]
Just turn on the Nuclear Siren for about 1 Minute and turn it off. The siren will seem to continue to rotate

**Comment by TheRealMcrafter** [comment]
Does this happen with the general siren also? Is this bug present in v4.0.0?

**Comment by TheRealMcrafter** [comment]
I have tried replicating it, and I cannot. Can you still do it?

**Comment by SirenFreak** [comment]
Yes.

**Comment by SirenFreak** [comment]
The issue seems to be fixed now.

**Comment by TheRealMcrafter** [comment]
Thank you.
